### 6.Dane tekstowe i API

In [20]:
import pandas as pd

In [1]:
#### Proste operacje tekstowe

In [7]:
tekst = 'Python'

In [8]:
tekst.upper()

'PYTHON'

In [9]:
tekst.lower()

'python'

In [14]:
tekst = ' Python '

In [15]:
tekst.lower()

' python '

In [16]:
tekst.strip()

'Python'

In [17]:
tekst.replace("P", "C")

' Cython '

In [18]:
napis = "1,3"

In [26]:
napis.replace(',', '.')

'1.3'

In [38]:
# adnotacja nt. "" i ''

print(f'Liczba: {napis} jest \'szczęśliwa\'')

Liczba: 1,3 jest 'szczęśliwa'

In [45]:
pd.to_numeric(napis.replace(',', '.'))

np.float64(1.3)

In [46]:
tekst.strip().count('P')

1

In [64]:
numer_tel = '999-999-999'

In [65]:
numer_tel.split('-')

['999', '999', '999']

In [66]:
#99999999
numer_tel = numer_tel.split('-')
numer_tel = ''.join(numer_tel)
numer_tel

'999999999'

In [67]:
words = ['sport', 'python', 'free', 'time']
joined_words = '#'.join(words)
print(joined_words)

sport#python#free#time

In [68]:
napis="prog.py"
print(napis.upper().split("."))

['PROG', 'PY']

In [69]:
nazwa="Python"
for n in nazwa:
    print(n)

P
y
t
h
o
n

In [70]:
lancuch="123456789"

In [71]:
lancuch[2]

'3'

In [72]:
lancuch[-1]

'9'

In [73]:
#### Dygresja na temat dat

In [74]:
data1 = '2024-01-01-14:00:00'
data2 = '2024-01-01-14:01:00'

In [75]:
data1 = pd.to_datetime(data1)
data2 = pd.to_datetime(data2)

In [76]:
type(data1)

pandas._libs.tslibs.timestamps.Timestamp

In [78]:
data2 - pd.Timedelta(seconds=60)

Timestamp('2024-01-01 14:00:00')

In [83]:
data2

Timestamp('2024-01-01 14:01:00')

In [80]:
data2.ceil('h')

Timestamp('2024-01-01 15:00:00')

In [82]:
data2.floor('h')

Timestamp('2024-01-01 14:00:00')

In [86]:
data2 - data1

Timedelta('0 days 00:01:00')

### Łączenie z API i pobieranie danych

Łączenie się z API (Application Programming Interface) i pobieranie danych to element analizy danych, który pozwala na dostęp do dynamicznych i często aktualizowanych źródeł informacji. API umożliwiają programistom komunikację z różnymi usługami internetowymi, takimi jak serwisy pogodowe, platformy społecznościowe czy bazy danych finansowych.

#### Podstawy łączenia się z API

API zazwyczaj działają na zasadzie wysyłania żądań HTTP i otrzymywania odpowiedzi, zazwyczaj w formacie JSON lub XML. W Pythonie najpopularniejszą biblioteką do wysyłania żądań HTTP jest `requests`.



### Podsumowanie

Łączenie się z API i pobieranie danych jest fundamentalnym aspektem analizy danych, pozwalającym na dostęp do dynamicznych i aktualizowanych źródeł informacji. Korzystanie z biblioteki `requests` w Pythonie umożliwia łatwe wysyłanie zapytań HTTP GET i POST, zarówno do publicznych API, jak i tych wymagających autoryzacji. Dzięki temu można pobierać, przetwarzać i analizować dane z różnorodnych źródeł, co jest kluczowe dla nowoczesnych aplikacji analitycznych i naukowych.

In [105]:
import pandas as pd
pd.set_option('display.max_rows', None)           # wszystkie wiersze
pd.set_option('display.max_columns', None)        # wszystkie kolumny
pd.set_option('display.max_colwidth', None)       # pełna szerokość kolumny
pd.set_option('display.width', None)              # pełna szerokość wyświetlania

### https://api.nbp.pl/

In [91]:
!pip install certifi

Requirement already satisfied: certifi in /Users/tomasz/Desktop/Analiza danych w Python/.venv/lib/python3.13/site-packages (2026.4.22)

In [92]:
import certifi
import ssl

ssl._create_default_https_context = ssl._create_unverified_context

In [122]:
import requests
import pandas as pd
from io import StringIO

response = requests.get('https://api.nbp.pl/api/exchangerates/rates/a/usd/', verify=False)
data = pd.read_json(StringIO(response.text))

In [123]:
data['rates'][0]['mid']

3.6167000000000002

In [124]:
waluta = 'USD'
start = '2026-01-01'
end = '2026-03-01'

In [127]:
response = requests.get('http://api.nbp.pl/api/exchangerates/rates/a/' + waluta +'/' + start + '/' + end + '/', verify=False)
zapytanie = pd.read_json(StringIO(response.text))
zapytanie

,table,currency,code,rates
0,A,dolar amerykański,USD,"{'no': '001/A/NBP/2026', 'effectiveDate': '2026-01-02', 'mid': 3.5963}"
1,A,dolar amerykański,USD,"{'no': '002/A/NBP/2026', 'effectiveDate': '2026-01-05', 'mid': 3.6045}"
2,A,dolar amerykański,USD,"{'no': '003/A/NBP/2026', 'effectiveDate': '2026-01-07', 'mid': 3.6035}"
3,A,dolar amerykański,USD,"{'no': '004/A/NBP/2026', 'effectiveDate': '2026-01-08', 'mid': 3.607}"
4,A,dolar amerykański,USD,"{'no': '005/A/NBP/2026', 'effectiveDate': '2026-01-09', 'mid': 3.6184}"
5,A,dolar amerykański,USD,"{'no': '006/A/NBP/2026', 'effectiveDate': '2026-01-12', 'mid': 3.6037}"
6,A,dolar amerykański,USD,"{'no': '007/A/NBP/2026', 'effectiveDate': '2026-01-13', 'mid': 3.6083}"
7,A,dolar amerykański,USD,"{'no': '008/A/NBP/2026', 'effectiveDate': '2026-01-14', 'mid': 3.614}"
8,A,dolar amerykański,USD,"{'no': '009/A/NBP/2026', 'effectiveDate': '2026-01-15', 'mid': 3.6153}"
9,A,dolar amerykański,USD,"{'no': '010/A/NBP/2026', 'effectiveDate': '2026-01-16', 'mid': 3.6346}"
10,A,dolar amerykański,USD,"{'no': '011/A/NBP/2026', 'effectiveDate': '2026-01-19', 'mid': 3.6331}"
11,A,dolar amerykański,USD,"{'no': '012/A/NBP/2026', 'effectiveDate': '2026-01-20', 'mid': 3.6054}"
12,A,dolar amerykański,USD,"{'no': '013/A/NBP/2026', 'effectiveDate': '2026-01-21', 'mid': 3.6118}"
13,A,dolar amerykański,USD,"{'no': '014/A/NBP/2026', 'effectiveDate': '2026-01-22', 'mid': 3.6028000000000002}"
14,A,dolar amerykański,USD,"{'no': '015/A/NBP/2026', 'effectiveDate': '2026-01-23', 'mid': 3.5831}"
15,A,dolar amerykański,USD,"{'no': '016/A/NBP/2026', 'effectiveDate': '2026-01-26', 'mid': 3.5499}"
16,A,dolar amerykański,USD,"{'no': '017/A/NBP/2026', 'effectiveDate': '2026-01-27', 'mid': 3.5354}"
17,A,dolar amerykański,USD,"{'no': '018/A/NBP/2026', 'effectiveDate': '2026-01-28', 'mid': 3.5045}"
18,A,dolar amerykański,USD,"{'no': '019/A/NBP/2026', 'effectiveDate': '2026-01-29', 'mid': 3.5189}"
19,A,dolar amerykański,USD,"{'no': '020/A/NBP/2026', 'effectiveDate': '2026-01-30', 'mid': 3.5379}"
20,A,dolar amerykański,USD,"{'no': '021/A/NBP/2026', 'effectiveDate': '2026-02-02', 'mid': 3.5495}"
21,A,dolar amerykański,USD,"{'no': '022/A/NBP/2026', 'effectiveDate': '2026-02-03', 'mid': 3.5785}"
22,A,dolar amerykański,USD,"{'no': '023/A/NBP/2026', 'effectiveDate': '2026-02-04', 'mid': 3.5755}"
23,A,dolar amerykański,USD,"{'no': '024/A/NBP/2026', 'effectiveDate': '2026-02-05', 'mid': 3.5799}"
24,A,dolar amerykański,USD,"{'no': '025/A/NBP/2026', 'effectiveDate': '2026-02-06', 'mid': 3.5749}"
25,A,dolar amerykański,USD,"{'no': '026/A/NBP/2026', 'effectiveDate': '2026-02-09', 'mid': 3.5527}"
26,A,dolar amerykański,USD,"{'no': '027/A/NBP/2026', 'effectiveDate': '2026-02-10', 'mid': 3.5377}"
27,A,dolar amerykański,USD,"{'no': '028/A/NBP/2026', 'effectiveDate': '2026-02-11', 'mid': 3.5387}"
28,A,dolar amerykański,USD,"{'no': '029/A/NBP/2026', 'effectiveDate': '2026-02-12', 'mid': 3.5441}"
29,A,dolar amerykański,USD,"{'no': '030/A/NBP/2026', 'effectiveDate': '2026-02-13', 'mid': 3.5528}"
30,A,dolar amerykański,USD,"{'no': '031/A/NBP/2026', 'effectiveDate': '2026-02-16', 'mid': 3.5467}"
31,A,dolar amerykański,USD,"{'no': '032/A/NBP/2026', 'effectiveDate': '2026-02-17', 'mid': 3.5607}"
32,A,dolar amerykański,USD,"{'no': '033/A/NBP/2026', 'effectiveDate': '2026-02-18', 'mid': 3.561}"
33,A,dolar amerykański,USD,"{'no': '034/A/NBP/2026', 'effectiveDate': '2026-02-19', 'mid': 3.578}"
34,A,dolar amerykański,USD,"{'no': '035/A/NBP/2026', 'effectiveDate': '2026-02-20', 'mid': 3.5898}"
35,A,dolar amerykański,USD,"{'no': '036/A/NBP/2026', 'effectiveDate': '2026-02-23', 'mid': 3.5737}"
36,A,dolar amerykański,USD,"{'no': '037/A/NBP/2026', 'effectiveDate': '2026-02-24', 'mid': 3.5793}"
37,A,dolar amerykański,USD,"{'no': '038/A/NBP/2026', 'effectiveDate': '2026-02-25', 'mid': 3.5785}"
38,A,dolar amerykański,USD,"{'no': '039/A/NBP/2026', 'effectiveDate': '2026-02-26', 'mid': 3.5792}"
39,A,dolar amerykański,USD,"{'no': '040/A/NBP/2026', 'effectiveDate': '2026-02-27', 'mid': 3.5804}"

In [128]:
k = zapytanie['rates'].values
k

array([{'no': '001/A/NBP/2026', 'effectiveDate': '2026-01-02', 'mid': 3.5963},
       {'no': '002/A/NBP/2026', 'effectiveDate': '2026-01-05', 'mid': 3.6045},
       {'no': '003/A/NBP/2026', 'effectiveDate': '2026-01-07', 'mid': 3.6035},
       {'no': '004/A/NBP/2026', 'effectiveDate': '2026-01-08', 'mid': 3.607},
       {'no': '005/A/NBP/2026', 'effectiveDate': '2026-01-09', 'mid': 3.6184},
       {'no': '006/A/NBP/2026', 'effectiveDate': '2026-01-12', 'mid': 3.6037},
       {'no': '007/A/NBP/2026', 'effectiveDate': '2026-01-13', 'mid': 3.6083},
       {'no': '008/A/NBP/2026', 'effectiveDate': '2026-01-14', 'mid': 3.614},
       {'no': '009/A/NBP/2026', 'effectiveDate': '2026-01-15', 'mid': 3.6153},
       {'no': '010/A/NBP/2026', 'effectiveDate': '2026-01-16', 'mid': 3.6346},
       {'no': '011/A/NBP/2026', 'effectiveDate': '2026-01-19', 'mid': 3.6331},
       {'no': '012/A/NBP/2026', 'effectiveDate': '2026-01-20', 'mid': 3.6054},
       {'no': '013/A/NBP/2026', 'effectiveDate': '2026-01-21', 'mid': 3.6118},
       {'no': '014/A/NBP/2026', 'effectiveDate': '2026-01-22', 'mid': 3.6028000000000002},
       {'no': '015/A/NBP/2026', 'effectiveDate': '2026-01-23', 'mid': 3.5831},
       {'no': '016/A/NBP/2026', 'effectiveDate': '2026-01-26', 'mid': 3.5499},
       {'no': '017/A/NBP/2026', 'effectiveDate': '2026-01-27', 'mid': 3.5354},
       {'no': '018/A/NBP/2026', 'effectiveDate': '2026-01-28', 'mid': 3.5045},
       {'no': '019/A/NBP/2026', 'effectiveDate': '2026-01-29', 'mid': 3.5189},
       {'no': '020/A/NBP/2026', 'effectiveDate': '2026-01-30', 'mid': 3.5379},
       {'no': '021/A/NBP/2026', 'effectiveDate': '2026-02-02', 'mid': 3.5495},
       {'no': '022/A/NBP/2026', 'effectiveDate': '2026-02-03', 'mid': 3.5785},
       {'no': '023/A/NBP/2026', 'effectiveDate': '2026-02-04', 'mid': 3.5755},
       {'no': '024/A/NBP/2026', 'effectiveDate': '2026-02-05', 'mid': 3.5799},
       {'no': '025/A/NBP/2026', 'effectiveDate': '2026-02-06', 'mid': 3.5749},
       {'no': '026/A/NBP/2026', 'effectiveDate': '2026-02-09', 'mid': 3.5527},
       {'no': '027/A/NBP/2026', 'effectiveDate': '2026-02-10', 'mid': 3.5377},
       {'no': '028/A/NBP/2026', 'effectiveDate': '2026-02-11', 'mid': 3.5387},
       {'no': '029/A/NBP/2026', 'effectiveDate': '2026-02-12', 'mid': 3.5441},
       {'no': '030/A/NBP/2026', 'effectiveDate': '2026-02-13', 'mid': 3.5528},
       {'no': '031/A/NBP/2026', 'effectiveDate': '2026-02-16', 'mid': 3.5467},
       {'no': '032/A/NBP/2026', 'effectiveDate': '2026-02-17', 'mid': 3.5607},
       {'no': '033/A/NBP/2026', 'effectiveDate': '2026-02-18', 'mid': 3.561},
       {'no': '034/A/NBP/2026', 'effectiveDate': '2026-02-19', 'mid': 3.578},
       {'no': '035/A/NBP/2026', 'effectiveDate': '2026-02-20', 'mid': 3.5898},
       {'no': '036/A/NBP/2026', 'effectiveDate': '2026-02-23', 'mid': 3.5737},
       {'no': '037/A/NBP/2026', 'effectiveDate': '2026-02-24', 'mid': 3.5793},
       {'no': '038/A/NBP/2026', 'effectiveDate': '2026-02-25', 'mid': 3.5785},
       {'no': '039/A/NBP/2026', 'effectiveDate': '2026-02-26', 'mid': 3.5792},
       {'no': '040/A/NBP/2026', 'effectiveDate': '2026-02-27', 'mid': 3.5804}],
      dtype=object)

In [129]:
l = []
data = []
for i, zap1 in enumerate(zapytanie['rates']):
    l.append(zap1['mid'])
    data.append(zap1['effectiveDate'])

In [131]:
test = pd.DataFrame(l, data).reset_index()
test.columns = ['data', 'cena']
test

          data    cena
0   2026-01-02  3.5963
1   2026-01-05  3.6045
2   2026-01-07  3.6035
3   2026-01-08  3.6070
4   2026-01-09  3.6184
5   2026-01-12  3.6037
6   2026-01-13  3.6083
7   2026-01-14  3.6140
8   2026-01-15  3.6153
9   2026-01-16  3.6346
10  2026-01-19  3.6331
11  2026-01-20  3.6054
12  2026-01-21  3.6118
13  2026-01-22  3.6028
14  2026-01-23  3.5831
15  2026-01-26  3.5499
16  2026-01-27  3.5354
17  2026-01-28  3.5045
18  2026-01-29  3.5189
19  2026-01-30  3.5379
20  2026-02-02  3.5495
21  2026-02-03  3.5785
22  2026-02-04  3.5755
23  2026-02-05  3.5799
24  2026-02-06  3.5749
25  2026-02-09  3.5527
26  2026-02-10  3.5377
27  2026-02-11  3.5387
28  2026-02-12  3.5441
29  2026-02-13  3.5528
30  2026-02-16  3.5467
31  2026-02-17  3.5607
32  2026-02-18  3.5610
33  2026-02-19  3.5780
34  2026-02-20  3.5898
35  2026-02-23  3.5737
36  2026-02-24  3.5793
37  2026-02-25  3.5785
38  2026-02-26  3.5792
39  2026-02-27  3.5804