### <a name='0'></a>Import biblioteki

In [1]:
import numpy as np
import pandas as pd

np.random.seed(42)
np.__version__

'2.3.5'

### <a name='1'></a> Ćwiczenie 21
Podany jest poniższy obiekt _DataFrame:_

```
df = pd.DataFrame(np.random.rand(10, 4), columns=list('ABCD'))
```

In [4]:
df = pd.DataFrame(np.random.rand(10, 4), columns=list('ABCD'))
df

          A         B         C         D
0  0.122038  0.495177  0.034389  0.909320
1  0.258780  0.662522  0.311711  0.520068
2  0.546710  0.184854  0.969585  0.775133
3  0.939499  0.894827  0.597900  0.921874
4  0.088493  0.195983  0.045227  0.325330
5  0.388677  0.271349  0.828738  0.356753
6  0.280935  0.542696  0.140924  0.802197
7  0.074551  0.986887  0.772245  0.198716
8  0.005522  0.815461  0.706857  0.729007
9  0.771270  0.074045  0.358466  0.115869

Wytnij wiersze obiektu _df_ dla których kolumna _C_ jest większa niż 0.8.  
Pomocniczo: Analogicznie jak w jezyku SQL poniższe zapytanie:


```
SELECT * FROM df WHERE C > 0.8
```

In [5]:
df[df['C'] > 0.8]

          A         B         C         D
2  0.546710  0.184854  0.969585  0.775133
5  0.388677  0.271349  0.828738  0.356753

### <a name='2'></a> Ćwiczenie 22

Wytnij wiersze obiektu _df_ dla których kolumna _C_ jest większa niż 0.3 oraz kolumna _D_ jest mniejsza niż 0.7.

In [6]:
df[(df['C'] > 0.3)&(df['D'] <0.7)]

          A         B         C         D
1  0.258780  0.662522  0.311711  0.520068
5  0.388677  0.271349  0.828738  0.356753
7  0.074551  0.986887  0.772245  0.198716
9  0.771270  0.074045  0.358466  0.115869

### <a name='3'></a> Ćwiczenie 23 - brak

### <a name='4'></a> Ćwiczenie 24
Ustaw wartość w wierszu o indeksie 3 dla kolumny B jako _np.nan_.
Wykorzystaj _df.iloc_.

In [7]:
df.iloc[3, df.columns.get_loc('B')] = np.nan

In [8]:
df

          A         B         C         D
0  0.122038  0.495177  0.034389  0.909320
1  0.258780  0.662522  0.311711  0.520068
2  0.546710  0.184854  0.969585  0.775133
3  0.939499       NaN  0.597900  0.921874
4  0.088493  0.195983  0.045227  0.325330
5  0.388677  0.271349  0.828738  0.356753
6  0.280935  0.542696  0.140924  0.802197
7  0.074551  0.986887  0.772245  0.198716
8  0.005522  0.815461  0.706857  0.729007
9  0.771270  0.074045  0.358466  0.115869

Ustaw wartość w wierszu o indeksie 8 dla kolumny D jako _np.nan_. Wykorzystaj _df.loc_.

In [10]:
df.loc[8, 'D'] = np.nan

In [11]:
df

          A         B         C         D
0  0.122038  0.495177  0.034389  0.909320
1  0.258780  0.662522  0.311711  0.520068
2  0.546710  0.184854  0.969585  0.775133
3  0.939499       NaN  0.597900  0.921874
4  0.088493  0.195983  0.045227  0.325330
5  0.388677  0.271349  0.828738  0.356753
6  0.280935  0.542696  0.140924  0.802197
7  0.074551  0.986887  0.772245  0.198716
8  0.005522  0.815461  0.706857       NaN
9  0.771270  0.074045  0.358466  0.115869

Wyświetl obiekt _df_.

In [12]:
df

          A         B         C         D
0  0.122038  0.495177  0.034389  0.909320
1  0.258780  0.662522  0.311711  0.520068
2  0.546710  0.184854  0.969585  0.775133
3  0.939499       NaN  0.597900  0.921874
4  0.088493  0.195983  0.045227  0.325330
5  0.388677  0.271349  0.828738  0.356753
6  0.280935  0.542696  0.140924  0.802197
7  0.074551  0.986887  0.772245  0.198716
8  0.005522  0.815461  0.706857       NaN
9  0.771270  0.074045  0.358466  0.115869

### <a name='5'></a> Ćwiczenie 25
Usuń wszystkie wiersze z obiektu _df_ zawierające braki danych i przypisz do zmiennej _df1_. Wyświetl zmienną _df1_.

__Wskazówka:__ pd.DataFrame().dropna()

In [13]:
df1 = df.dropna()
df1

          A         B         C         D
0  0.122038  0.495177  0.034389  0.909320
1  0.258780  0.662522  0.311711  0.520068
2  0.546710  0.184854  0.969585  0.775133
4  0.088493  0.195983  0.045227  0.325330
5  0.388677  0.271349  0.828738  0.356753
6  0.280935  0.542696  0.140924  0.802197
7  0.074551  0.986887  0.772245  0.198716
9  0.771270  0.074045  0.358466  0.115869

### <a name='6'></a> Ćwiczenie 26
Zauważ, że indeks po usunięciu dwóch wierszy w obiekcie _df1_ nie jest po kolei. Zresetuj indeks, aby wprowadzić kolejność (nie dodawaj nowej kolumny, tylko zreseuj indeks). Wyświetl zmienną _df1_.

In [14]:
df1.reset_index(drop=True, inplace=True)
df1

          A         B         C         D
0  0.122038  0.495177  0.034389  0.909320
1  0.258780  0.662522  0.311711  0.520068
2  0.546710  0.184854  0.969585  0.775133
3  0.088493  0.195983  0.045227  0.325330
4  0.388677  0.271349  0.828738  0.356753
5  0.280935  0.542696  0.140924  0.802197
6  0.074551  0.986887  0.772245  0.198716
7  0.771270  0.074045  0.358466  0.115869

### <a name='7'></a> Ćwiczenie 27
Wracamy do obiektu _df_. Wyznacz liczbę brakujących elementów w obiekcie _df_ dla każdej kolumny.

In [17]:
df.isna().sum()

A    0
B    1
C    0
D    1
dtype: int64

### <a name='8'></a> Ćwiczenie 28
Uzupełnij brakujące wartości wartością 0 i przypisz do zmiennej _df_.

In [18]:
df = df.fillna(0)
df

          A         B         C         D
0  0.122038  0.495177  0.034389  0.909320
1  0.258780  0.662522  0.311711  0.520068
2  0.546710  0.184854  0.969585  0.775133
3  0.939499  0.000000  0.597900  0.921874
4  0.088493  0.195983  0.045227  0.325330
5  0.388677  0.271349  0.828738  0.356753
6  0.280935  0.542696  0.140924  0.802197
7  0.074551  0.986887  0.772245  0.198716
8  0.005522  0.815461  0.706857  0.000000
9  0.771270  0.074045  0.358466  0.115869

### <a name='9'></a> Ćwiczenie 29
Zamień kolejność kolumn w obiekcie _df_ na podaną poniżej:
* D, A, B, C  

i przypisz do zmiennej _df_.

In [19]:
df = df[['D', 'A', 'B', 'C']]
df

          D         A         B         C
0  0.909320  0.122038  0.495177  0.034389
1  0.520068  0.258780  0.662522  0.311711
2  0.775133  0.546710  0.184854  0.969585
3  0.921874  0.939499  0.000000  0.597900
4  0.325330  0.088493  0.195983  0.045227
5  0.356753  0.388677  0.271349  0.828738
6  0.802197  0.280935  0.542696  0.140924
7  0.198716  0.074551  0.986887  0.772245
8  0.000000  0.005522  0.815461  0.706857
9  0.115869  0.771270  0.074045  0.358466

### <a name='10'></a> Ćwiczenie 30
Usuń kolumnę $D$ z obiektu _df_.

In [22]:
df = df.drop('D', axis=1)

In [23]:
df

          A         B         C
0  0.122038  0.495177  0.034389
1  0.258780  0.662522  0.311711
2  0.546710  0.184854  0.969585
3  0.939499  0.000000  0.597900
4  0.088493  0.195983  0.045227
5  0.388677  0.271349  0.828738
6  0.280935  0.542696  0.140924
7  0.074551  0.986887  0.772245
8  0.005522  0.815461  0.706857
9  0.771270  0.074045  0.358466