### <a name='0'></a>Import biblioteki

In [38]:
import numpy as np
import pandas as pd

pd.options.display.float_format = '{:.2f}'.format
np.__version__

'2.3.5'

### <a name='1'></a> Ćwiczenie 51
Wczytaj do obiektu _DataFrame_ o nazwie _df_ plik data.csv.

Opis danych:

* https://www.kaggle.com/datasets/sujay1844/used-car-prices

Ustaw indeks obiektu _df_ na pierwszą kolumnę (parametr 'index_col=0'). Wyświetl obiekt _df_.

In [39]:
df = pd.read_csv('data.csv', index_col=0)
df

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.00,NaN,1.75
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.00,NaN,12.50
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.00,8.61 Lakh,4.50
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.00,NaN,6.00
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.00,NaN,17.74
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6014,Maruti Swift VDI,Delhi,2014,27365,Diesel,Manual,First,28.4 kmpl,1248 CC,74 bhp,5.00,7.88 Lakh,4.75
6015,Hyundai Xcent 1.1 CRDi S,Jaipur,2015,100000,Diesel,Manual,First,24.4 kmpl,1120 CC,71 bhp,5.00,NaN,4.00
6016,Mahindra Xylo D4 BSIV,Jaipur,2012,55000,Diesel,Manual,Second,14.0 kmpl,2498 CC,112 bhp,8.00,NaN,2.90
6017,Maruti Wagon R VXI,Kolkata,2013,46000,Petrol,Manual,First,18.9 kmpl,998 CC,67.1 bhp,5.00,NaN,2.65
6018,Chevrolet Beat Diesel,Hyderabad,2011,47000,Diesel,Manual,First,25.44 kmpl,936 CC,57.6 bhp,5.00,NaN,2.50

Wyświetl informacje na temat obiektu _df_.

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6019 entries, 0 to 6018
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               6019 non-null   object
 1   Location           6019 non-null   object
 2   Year               6019 non-null   int64
 3   Kilometers_Driven  6019 non-null   int64
 4   Fuel_Type          6019 non-null   object
 5   Transmission       6019 non-null   object
 6   Owner_Type         6019 non-null   object
 7   Mileage            6017 non-null   object
 8   Engine             5983 non-null   object
 9   Power              5983 non-null   object
 10  Seats              5977 non-null   float64
 11  New_Price          824 non-null    object
 12  Price              6019 non-null   float64
dtypes: float64(2), int64(2), object(9)
memory usage: 658.3+ KB

Wyświetl podstawowe statystyki obiektu _df_.

In [5]:
df.describe()

         Year  Kilometers_Driven   Seats   Price
count 6019.00            6019.00 5977.00 6019.00
mean  2013.36           58738.38    5.28    9.48
std      3.27           91268.84    0.81   11.19
min   1998.00             171.00    0.00    0.44
25%   2011.00           34000.00    5.00    3.50
50%   2014.00           53000.00    5.00    5.64
75%   2016.00           73000.00    5.00    9.95
max   2019.00         6500000.00   10.00  160.00

In [6]:
df.describe(include='object')

,Name,Location,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,New_Price
count,6019,6019,6019,6019,6019,6017,5983,5983,824
unique,1876,11,5,2,4,442,146,372,540
top,Mahindra XUV500 W8 2WD,Mumbai,Diesel,Manual,First,18.9 kmpl,1197 CC,74 bhp,95.13 Lakh
freq,49,790,3205,4299,4929,172,606,235,6

In [7]:
df.isna().sum()

Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 36
Power                  36
Seats                  42
New_Price            5195
Price                   0
dtype: int64

### <a name='2'></a> Ćwiczenie 52
Wypisz listę zawierającą nazwy wszystkich kolumn obiektu _df_.

In [8]:
list(df.columns)

['Name',
 'Location',
 'Year',
 'Kilometers_Driven',
 'Fuel_Type',
 'Transmission',
 'Owner_Type',
 'Mileage',
 'Engine',
 'Power',
 'Seats',
 'New_Price',
 'Price']

Z obiektu _df_ usuń kolumnę o nazwie _New_Price_ i wyświetl 5 pierwszych wierszy.

In [9]:
df.drop('New_Price', axis=1, inplace=True)
df.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.00,1.75
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.00,12.50
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.00,4.50
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.00,6.00
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.00,17.74

### <a name='3'></a> Ćwiczenie 53
Znajdź liczbę brakujących wartości dla każdej zmiennej obiektu _df_.

In [10]:
df.isnull().sum()

Name                  0
Location              0
Year                  0
Kilometers_Driven     0
Fuel_Type             0
Transmission          0
Owner_Type            0
Mileage               2
Engine               36
Power                36
Seats                42
Price                 0
dtype: int64

Usuń wszystkie wiersze z obiektu _df_ zawierające braki danych. Użyj parametru _inplace=True_.

In [11]:
df.dropna(inplace=True)

Wyświetl raz jeszcze informacje na temat obiektu _df_. Zwróć uwagę na liczbę wierszy i typ danych.

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5975 entries, 0 to 6018
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               5975 non-null   object
 1   Location           5975 non-null   object
 2   Year               5975 non-null   int64
 3   Kilometers_Driven  5975 non-null   int64
 4   Fuel_Type          5975 non-null   object
 5   Transmission       5975 non-null   object
 6   Owner_Type         5975 non-null   object
 7   Mileage            5975 non-null   object
 8   Engine             5975 non-null   object
 9   Power              5975 non-null   object
 10  Seats              5975 non-null   float64
 11  Price              5975 non-null   float64
dtypes: float64(2), int64(2), object(8)
memory usage: 606.8+ KB

### <a name='4'></a> Ćwiczenie 54
Zamień wszystkie litery w nazwach kolumn na małe, np.:
* Name -> name
* Fuel_Type -> fuel_type  

Wyświetl metodą _head()_ pięć pierwszych wierszy.

In [13]:
df.columns = [col.lower() for col in df.columns]
df.head()

,name,location,year,kilometers_driven,fuel_type,transmission,owner_type,mileage,engine,power,seats,price
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.00,1.75
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.00,12.50
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.00,4.50
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.00,6.00
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.00,17.74

### <a name='5'></a> Ćwiczenie 55
Znajdź rozkład wartości zmiennej _owner_type_.

In [14]:
df['owner_type'].value_counts()

owner_type
First             4903
Second             953
Third              111
Fourth & Above       8
Name: count, dtype: int64

Znajdź rozkład wartości zmiennej _engine_.

In [15]:
df['engine'].value_counts()

engine
1197 CC    606
1248 CC    512
1498 CC    303
998 CC     259
2179 CC    240
          ...
1489 CC      1
1422 CC      1
1978 CC      1
2694 CC      1
1797 CC      1
Name: count, Length: 145, dtype: int64

In [16]:
df.dtypes

name                  object
location              object
year                   int64
kilometers_driven      int64
fuel_type             object
transmission          object
owner_type            object
mileage               object
engine                object
power                 object
seats                float64
price                float64
dtype: object

Zauważ, że zmienna _engine_ jest typu _object_. Usuń 3 ostatnie znaki z każdego elementu i resztę skonwertuj na typ int. Wyświetl metodą _head()_ pięć pierwszych wierszy.

__Wskazówka__: metoda pd.DataFrame().map(lamdba x: ...)

In [17]:
df['engine'] = df['engine'].map(lambda x: int(x[:-3]))
df.head()

,name,location,year,kilometers_driven,fuel_type,transmission,owner_type,mileage,engine,power,seats,price
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998,58.16 bhp,5.00,1.75
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582,126.2 bhp,5.00,12.50
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199,88.7 bhp,5.00,4.50
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248,88.76 bhp,7.00,6.00
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968,140.8 bhp,5.00,17.74

### <a name='6'></a> Ćwiczenie 56 - rozwiązane
Spójrz na rozkład zmiennej _power_. Zauważ, że ta zmienna ma także braki danych w postaci wartości _'null bhp'_. Zamień te wartości dla zmiennej _power_ na wartość _np.nan_. Wykorzystaj przy tym funkcję _np.where()_.

In [18]:
df['power'].value_counts()

power
74 bhp        235
98.6 bhp      131
73.9 bhp      125
140 bhp       123
78.9 bhp      111
             ...
201 bhp         1
199.3 bhp       1
95 bhp          1
152.88 bhp      1
181.04 bhp      1
Name: count, Length: 371, dtype: int64

In [19]:
counts = df['power'].value_counts()

In [20]:
counts

power
74 bhp        235
98.6 bhp      131
73.9 bhp      125
140 bhp       123
78.9 bhp      111
             ...
201 bhp         1
199.3 bhp       1
95 bhp          1
152.88 bhp      1
181.04 bhp      1
Name: count, Length: 371, dtype: int64

In [21]:
counts[counts.index.str.contains('null')]

power
null bhp    103
Name: count, dtype: int64

In [22]:
np.where(df['power'] == 'null bhp') #indeksy

(array([  76,   79,   89,  120,  143,  225,  242,  259,  304,  305,  383,
         421,  425,  440,  469,  572,  628,  644,  645,  735,  744,  824,
         910,  921,  929, 1063, 1138, 1148, 1266, 1313, 1338, 1380, 1411,
        1546, 1569, 1640, 1663, 1848, 1989, 2043, 2118, 2152, 2250, 2254,
        2292, 2328, 2377, 2425, 2434, 2481, 2485, 2511, 2561, 2579, 2616,
        2621, 2868, 3010, 3038, 3081, 3166, 3224, 3266, 3414, 3491, 3506,
        3562, 3601, 3611, 3618, 3642, 3706, 3868, 3900, 3969, 4046, 4049,
        4318, 4321, 4593, 4672, 4676, 4706, 4792, 4848, 4862, 4914, 5024,
        5078, 5186, 5383, 5395, 5415, 5486, 5490, 5604, 5712, 5716, 5818,
        5830, 5881, 5899, 5941]),)

In [23]:
df[df.power.index == 76]

,name,location,year,kilometers_driven,fuel_type,transmission,owner_type,mileage,engine,power,seats,price
76,Ford Fiesta 1.4 SXi TDCi,Jaipur,2008,111111,Diesel,Manual,First,17.8 kmpl,1399,null bhp,5.00,2.00

In [24]:
df['power'] = np.where(df['power'] == 'null bhp', np.nan, df['power'])

In [25]:
df.isna().sum()

name                   0
location               0
year                   0
kilometers_driven      0
fuel_type              0
transmission           0
owner_type             0
mileage                0
engine                 0
power                103
seats                  0
price                  0
dtype: int64

Usuń jeszcze raz wszystkie rekordy z brakami danych.

In [26]:
df.dropna(inplace=True)

In [27]:
df.isnull().sum()

name                 0
location             0
year                 0
kilometers_driven    0
fuel_type            0
transmission         0
owner_type           0
mileage              0
engine               0
power                0
seats                0
price                0
dtype: int64

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5872 entries, 0 to 6018
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   name               5872 non-null   object
 1   location           5872 non-null   object
 2   year               5872 non-null   int64
 3   kilometers_driven  5872 non-null   int64
 4   fuel_type          5872 non-null   object
 5   transmission       5872 non-null   object
 6   owner_type         5872 non-null   object
 7   mileage            5872 non-null   object
 8   engine             5872 non-null   int64
 9   power              5872 non-null   object
 10  seats              5872 non-null   float64
 11  price              5872 non-null   float64
dtypes: float64(2), int64(3), object(7)
memory usage: 596.4+ KB

### <a name='7'></a> Ćwiczenie 57
Zauważ, że zmienna _power_ jest typu _object_. Usuń 4 ostatnie znaki z każdego elementu i resztę skonwertuj na typ float.

Wyświetl metodą _head()_ pięć pierwszych wierszy.

__Wskazówka__: metoda pd.DataFrame().map(lamdba x: ...)

In [29]:
df['power']

0       58.16 bhp
1       126.2 bhp
2        88.7 bhp
3       88.76 bhp
4       140.8 bhp
          ...
6014       74 bhp
6015       71 bhp
6016      112 bhp
6017     67.1 bhp
6018     57.6 bhp
Name: power, Length: 5872, dtype: object

In [30]:
df['power'] = df['power'].map(lambda x: float(x[:-4]))
df.head()

,name,location,year,kilometers_driven,fuel_type,transmission,owner_type,mileage,engine,power,seats,price
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998,58.16,5.00,1.75
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582,126.20,5.00,12.50
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199,88.70,5.00,4.50
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248,88.76,7.00,6.00
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968,140.80,5.00,17.74

### <a name='8'></a> Ćwiczenie 58
Pogrupuj dane na poziomie roku (_year_) i policz liczbę rekordów dla każdego roku w obiekcie _df_.

In [31]:
df.groupby('year').size()

year
1998      3
1999      2
2000      4
2001      4
2002     11
2003     14
2004     25
2005     42
2006     66
2007    105
2008    162
2009    191
2010    333
2011    452
2012    562
2013    639
2014    794
2015    740
2016    737
2017    586
2018    298
2019    102
dtype: int64

### <a name='9'></a> Ćwiczenie 59
Sprawdź rozkład zmiennej _transmission_.

In [32]:
df['transmission'].value_counts()

transmission
Manual       4170
Automatic    1702
Name: count, dtype: int64

Dokonaj następującego mapowania zmiennej _transmission_:
* Manual -> 0
* Automatic -> 1

Wyświetl metodą _head()_ pięć pierwszych wierszy.

__Wskazówka__: metoda pd.DataFrame().map(lamdba x: ...)

In [33]:
df['transmission'] = df['transmission'].map({'Manual': 0, 'Automatic': 1})
df.head()

,name,location,year,kilometers_driven,fuel_type,transmission,owner_type,mileage,engine,power,seats,price
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,0,First,26.6 km/kg,998,58.16,5.00,1.75
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,0,First,19.67 kmpl,1582,126.20,5.00,12.50
2,Honda Jazz V,Chennai,2011,46000,Petrol,0,First,18.2 kmpl,1199,88.70,5.00,4.50
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,0,First,20.77 kmpl,1248,88.76,7.00,6.00
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,1,Second,15.2 kmpl,1968,140.80,5.00,17.74

In [34]:
df

,name,location,year,kilometers_driven,fuel_type,transmission,owner_type,mileage,engine,power,seats,price
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,0,First,26.6 km/kg,998,58.16,5.00,1.75
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,0,First,19.67 kmpl,1582,126.20,5.00,12.50
2,Honda Jazz V,Chennai,2011,46000,Petrol,0,First,18.2 kmpl,1199,88.70,5.00,4.50
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,0,First,20.77 kmpl,1248,88.76,7.00,6.00
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,1,Second,15.2 kmpl,1968,140.80,5.00,17.74
...,...,...,...,...,...,...,...,...,...,...,...,...
6014,Maruti Swift VDI,Delhi,2014,27365,Diesel,0,First,28.4 kmpl,1248,74.00,5.00,4.75
6015,Hyundai Xcent 1.1 CRDi S,Jaipur,2015,100000,Diesel,0,First,24.4 kmpl,1120,71.00,5.00,4.00
6016,Mahindra Xylo D4 BSIV,Jaipur,2012,55000,Diesel,0,Second,14.0 kmpl,2498,112.00,8.00,2.90
6017,Maruti Wagon R VXI,Kolkata,2013,46000,Petrol,0,First,18.9 kmpl,998,67.10,5.00,2.65
6018,Chevrolet Beat Diesel,Hyderabad,2011,47000,Diesel,0,First,25.44 kmpl,936,57.60,5.00,2.50

### <a name='10'></a> Ćwiczenie 60
Zapisz obiekt _df_ do pliku _car.csv_ (nie zapisuj indeksu - parametr (index=False)).

In [35]:
df.to_csv('car.csv', index=False)

In [36]:
df

,name,location,year,kilometers_driven,fuel_type,transmission,owner_type,mileage,engine,power,seats,price
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,0,First,26.6 km/kg,998,58.16,5.00,1.75
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,0,First,19.67 kmpl,1582,126.20,5.00,12.50
2,Honda Jazz V,Chennai,2011,46000,Petrol,0,First,18.2 kmpl,1199,88.70,5.00,4.50
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,0,First,20.77 kmpl,1248,88.76,7.00,6.00
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,1,Second,15.2 kmpl,1968,140.80,5.00,17.74
...,...,...,...,...,...,...,...,...,...,...,...,...
6014,Maruti Swift VDI,Delhi,2014,27365,Diesel,0,First,28.4 kmpl,1248,74.00,5.00,4.75
6015,Hyundai Xcent 1.1 CRDi S,Jaipur,2015,100000,Diesel,0,First,24.4 kmpl,1120,71.00,5.00,4.00
6016,Mahindra Xylo D4 BSIV,Jaipur,2012,55000,Diesel,0,Second,14.0 kmpl,2498,112.00,8.00,2.90
6017,Maruti Wagon R VXI,Kolkata,2013,46000,Petrol,0,First,18.9 kmpl,998,67.10,5.00,2.65
6018,Chevrolet Beat Diesel,Hyderabad,2011,47000,Diesel,0,First,25.44 kmpl,936,57.60,5.00,2.50

### Model predykcji cen samochodów

Budowa modelu do przewidywania cen na zbiorze treningowym i testowym

In [49]:
categorical_cols

['Name',
 'Location',
 'Fuel_Type',
 'Transmission',
 'Owner_Type',
 'Mileage',
 'Engine',
 'Power',
 'New_Price']

In [53]:
df_model

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,1200.00,9.00,2010.00,72000.00,0.00,1.00,0.00,403.00,144.00,260.00,5.00,540.00,1.75
1,512.00,10.00,2015.00,41000.00,1.00,1.00,0.00,275.00,39.00,56.00,5.00,540.00,12.50
2,486.00,2.00,2011.00,46000.00,4.00,1.00,0.00,232.00,12.00,344.00,5.00,481.00,4.50
3,1059.00,2.00,2012.00,87000.00,1.00,1.00,0.00,308.00,14.00,346.00,7.00,540.00,6.00
4,23.00,3.00,2013.00,40670.00,1.00,0.00,2.00,135.00,58.00,76.00,5.00,540.00,17.74
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6014,1159.00,4.00,2014.00,27365.00,1.00,1.00,0.00,413.00,14.00,299.00,5.00,440.00,4.75
6015,668.00,6.00,2015.00,100000.00,1.00,1.00,0.00,377.00,3.00,290.00,5.00,540.00,4.00
6016,932.00,6.00,2012.00,55000.00,1.00,1.00,2.00,91.00,93.00,30.00,8.00,540.00,2.90
6017,1207.00,8.00,2013.00,46000.00,4.00,1.00,0.00,253.00,144.00,282.00,5.00,540.00,2.65
6018,165.00,5.00,2011.00,47000.00,1.00,1.00,0.00,391.00,140.00,259.00,5.00,540.00,2.50

In [44]:
# Przygotowanie danych - konwersja zmiennych kategorycznych
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer

df_model = df.copy()

# Identyfikuj kolumny kategoryczne (oprócz price i tych już numerycznych)
categorical_cols = df_model.select_dtypes(include=['object']).columns.tolist()
print(f"Kolumny kategoryczne: {categorical_cols}")

# Kodowanie zmiennych kategorycznych za pomocą LabelEncoder
for col in categorical_cols:
    le = LabelEncoder()
    df_model[col] = le.fit_transform(df_model[col])

# Obsługa brakujących wartości (NaN)
print(f"\nBrakujące wartości przed imputacją:\n{df_model.isnull().sum()}")

# Imputacja - zastąpienie NaN medianą dla każdej kolumny
imputer = SimpleImputer(strategy='median')
df_model_imputed = pd.DataFrame(
    imputer.fit_transform(df_model),
    columns=df_model.columns
)

print(f"\nBrakujące wartości po imputacji:\n{df_model_imputed.isnull().sum()}")

print("\nDane po transformacji:")
print(df_model_imputed.dtypes)
print("\nPierwsze 5 wierszy:")
print(df_model_imputed.head())

df_model = df_model_imputed

Kolumny kategoryczne: ['Name', 'Location', 'Fuel_Type', 'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'New_Price']

Brakujące wartości przed imputacją:
Name                  0
Location              0
Year                  0
Kilometers_Driven     0
Fuel_Type             0
Transmission          0
Owner_Type            0
Mileage               0
Engine                0
Power                 0
Seats                42
New_Price             0
Price                 0
dtype: int64

Brakujące wartości po imputacji:
Name                 0
Location             0
Year                 0
Kilometers_Driven    0
Fuel_Type            0
Transmission         0
Owner_Type           0
Mileage              0
Engine               0
Power                0
Seats                0
New_Price            0
Price                0
dtype: int64

Dane po transformacji:
Name                 float64
Location             float64
Year                 float64
Kilometers_Driven    float64
Fuel_Type            float64
Transmission         float64
Owner_Type           float64
Mileage              float64
Engine               float64
Power                float64
Seats                float64
New_Price            float64
Price                float64
dtype: object

Pierwsze 5 wierszy:
     Name  Location    Year  Kilometers_Driven  Fuel_Type  Transmission  \
0 1200.00      9.00 2010.00           72000.00       0.00          1.00
1  512.00     10.00 2015.00           41000.00       1.00          1.00
2  486.00      2.00 2011.00           46000.00       4.00          1.00
3 1059.00      2.00 2012.00           87000.00       1.00          1.00
4   23.00      3.00 2013.00           40670.00       1.00          0.00

   Owner_Type  Mileage  Engine  Power  Seats  New_Price  Price
0        0.00   403.00  144.00 260.00   5.00     540.00   1.75
1        0.00   275.00   39.00  56.00   5.00     540.00  12.50
2        0.00   232.00   12.00 344.00   5.00     481.00   4.50
3        0.00   308.00   14.00 346.00   7.00     540.00   6.00
4        2.00   135.00   58.00  76.00   5.00     540.00  17.74

In [45]:
# Podział na zbiór treningowy i testowy
from sklearn.model_selection import train_test_split

# Sprawdzenie dostępnych kolumn
print("Dostępne kolumny:", df_model.columns.tolist())

# Separacja zmiennych niezależnych (X) i zmiennej docelowej (y)
# Używamy 'Price' z dużą literą
X = df_model.drop('Price', axis=1)
y = df_model['Price']

# Podział: 80% trenowanie, 20% testowanie
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(f"Zbiór treningowy: {X_train.shape[0]} próbek")
print(f"Zbiór testowy: {X_test.shape[0]} próbek")
print(f"\nZmienne niezależne (X):\n{X.columns.tolist()}")

Dostępne kolumny: ['Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type', 'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats', 'New_Price', 'Price']
Zbiór treningowy: 4815 próbek
Zbiór testowy: 1204 próbek

Zmienne niezależne (X):
['Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type', 'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats', 'New_Price']

In [46]:
# Budowa i trening modelu
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression

# Model 1: LinearRegression (regresja liniowa)
model_lr = LinearRegression()
model_lr.fit(X_train, y_train)
print("✓ Model LinearRegression wytrenowany")

# Model 2: RandomForestRegressor (las losowy)
model_rf = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
model_rf.fit(X_train, y_train)
print("✓ Model RandomForestRegressor wytrenowany")

✓ Model LinearRegression wytrenowany
✓ Model RandomForestRegressor wytrenowany

In [47]:
# Predykcje na zbiorze testowym
y_pred_lr = model_lr.predict(X_test)
y_pred_rf = model_rf.predict(X_test)

# Porównanie predykcji z wartościami rzeczywistymi
predictions_df = pd.DataFrame({
    'Rzeczywista cena': y_test.values,
    'Predykcja LR': y_pred_lr,
    'Predykcja RF': y_pred_rf
})

print("Pierwsze 10 predykcji na zbiorze testowym:")
print(predictions_df.head(10))

Pierwsze 10 predykcji na zbiorze testowym:
   Rzeczywista cena  Predykcja LR  Predykcja RF
0              5.75          3.80          5.30
1             10.08         13.22         12.73
2              7.85         10.03          7.99
3              2.40          5.27          2.33
4              1.60         11.70         11.54
5              2.60         12.61          3.63
6              5.55          7.73          5.34
7              3.11          2.92          3.74
8             12.50         19.88         14.02
9              3.90         -2.80          4.28

In [48]:
# Ocena modeli
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

print("="*60)
print("OCENA MODELU LINEAR REGRESSION")
print("="*60)
mse_lr = mean_squared_error(y_test, y_pred_lr)
mae_lr = mean_absolute_error(y_test, y_pred_lr)
r2_lr = r2_score(y_test, y_pred_lr)

print(f"Mean Squared Error (MSE): {mse_lr:.2f}")
print(f"Mean Absolute Error (MAE): {mae_lr:.2f}")
print(f"R² Score: {r2_lr:.4f}")
print(f"Root Mean Squared Error (RMSE): {np.sqrt(mse_lr):.2f}")

print("\n" + "="*60)
print("OCENA MODELU RANDOM FOREST")
print("="*60)
mse_rf = mean_squared_error(y_test, y_pred_rf)
mae_rf = mean_absolute_error(y_test, y_pred_rf)
r2_rf = r2_score(y_test, y_pred_rf)

print(f"Mean Squared Error (MSE): {mse_rf:.2f}")
print(f"Mean Absolute Error (MAE): {mae_rf:.2f}")
print(f"R² Score: {r2_rf:.4f}")
print(f"Root Mean Squared Error (RMSE): {np.sqrt(mse_rf):.2f}")

print("\n" + "="*60)
print("PODSUMOWANIE")
print("="*60)
if r2_rf > r2_lr:
    print("✓ Model RandomForest daje lepsze wyniki!")
else:
    print("✓ Model LinearRegression daje lepsze wyniki!")

============================================================
OCENA MODELU LINEAR REGRESSION
============================================================
Mean Squared Error (MSE): 88.75
Mean Absolute Error (MAE): 4.77
R² Score: 0.2788
Root Mean Squared Error (RMSE): 9.42

============================================================
OCENA MODELU RANDOM FOREST
============================================================
Mean Squared Error (MSE): 17.85
Mean Absolute Error (MAE): 1.65
R² Score: 0.8550
Root Mean Squared Error (RMSE): 4.22

============================================================
PODSUMOWANIE
============================================================
✓ Model RandomForest daje lepsze wyniki!