# Letnie igrzyska olimpijskie

### 1.

Wczytaj tabelę z dokonaniami medalowymi 'summer_1976_2008.pkl'.

In [1]:
import pandas as pd
olimp = pd.read_pickle(r"summer_1976_2008.pkl")
olimp

,City,Year,Sport,Discipline,Event,Athlete,Gender,Country_Code,Country,Event_gender,Medal
0,Montreal,1976,Aquatics,Diving,3m springboard,"KÖHLER, Christa",Women,GDR,East Germany,W,Silver
1,Montreal,1976,Aquatics,Diving,3m springboard,"KOSENKOV, Aleksandr",Men,URS,Soviet Union,M,Bronze
2,Montreal,1976,Aquatics,Diving,3m springboard,"BOGGS, Philip George",Men,USA,United States,M,Gold
3,Montreal,1976,Aquatics,Diving,3m springboard,"CAGNOTTO, Giorgio Franco",Men,ITA,Italy,M,Silver
4,Montreal,1976,Aquatics,Diving,10m platform,"WILSON, Deborah Keplar",Women,USA,United States,W,Bronze
...,...,...,...,...,...,...,...,...,...,...,...
15428,Beijing,2008,Wrestling,Wrestling Gre-R,66 - 74kg,"GUENOT, Christophe",Men,FRA,France,M,Bronze
15429,Beijing,2008,Wrestling,Wrestling Gre-R,66 - 74kg,"KVIRKELIA, Manuchar",Men,GEO,Georgia,M,Gold
15430,Beijing,2008,Wrestling,Wrestling Gre-R,55 - 60kg,"RAHIMOV, Vitaliy",Men,AZE,Azerbaijan,M,Silver
15431,Beijing,2008,Wrestling,Wrestling Gre-R,60 - 66kg,"GUENOT, Steeve",Men,FRA,France,M,Gold
15432,Beijing,2008,Wrestling,Wrestling Gre-R,96 - 120kg,"LOPEZ, Mijain",Men,CUB,Cuba,M,Gold

In [72]:
pd.set_option('display.precision', 1)

### 2.


Ile kobiet i ilu mężczyzn wzięło udział w zmaganiach olimpijskich?

In [3]:
olimp.Gender.value_counts()

Gender
Men      9388
Women    5928
Name: count, dtype: Int64

### 3.


Ile kobiet i ile mężczyzn wzięło udział w zmaganiach olimpijskich w poszczególnych latach?

In [54]:
o = olimp.groupby('Year').Gender.value_counts()
o = o.reset_index()
m = o[o.Gender == 'Men']['count']
m = m.reset_index(drop=True)
m

0     924
1     958
2     973
3    1011
4    1105
5    1082
6    1126
7    1099
8    1110
Name: count, dtype: int64

In [55]:
o = olimp.groupby('Year').Gender.value_counts()
o = o.reset_index()
o = o[o.Gender == 'Women']['count'] 
o = o.reset_index(drop=True)
o

0    381
1    429
2    486
3    535
4    600
5    777
6    889
7    899
8    932
Name: count, dtype: int64

In [57]:
result = pd.concat([o, m], axis=1)
result

   count  count
0    381    924
1    429    958
2    486    973
3    535   1011
4    600   1105
5    777   1082
6    889   1126
7    899   1099
8    932   1110

In [66]:
x = olimp.groupby(["Gender","Year"]).size().unstack(0)
x

Gender   Men  Women
Year
1976     924    381
1980     958    429
1984     973    486
1988    1011    535
1992    1105    600
1996    1082    777
2000    1126    889
2004    1099    899
2008    1110    932

### 4.


Utwórz ramkę z procentowym udziałem kobiet względem poszczególnych lat, w których odbywały się igrzyska.

In [73]:
x["% Women"] = (x.Women/(x.Men + x.Women) * 100)
x

Gender   Men  Women  % Women
Year
1976     924    381     29.2
1980     958    429     30.9
1984     973    486     33.3
1988    1011    535     34.6
1992    1105    600     35.2
1996    1082    777     41.8
2000    1126    889     44.1
2004    1099    899     45.0
2008    1110    932     45.6

### 5. 


Wyświetl ramkę 10 najbardziej utytułowanych medalistów zgodnie z rankingiem:
* brąz -- 1 punkt,
* srebro -- 2 punkty,
* złoto -- 6 punktów

In [76]:
olimp.groupby(['Athlete', 'Medal']).size().unstack().fillna(0).astype('int')

Medal                  Bronze  Gold  Silver
Athlete
AAMODT, Ragnhild            0     1       0
AARDENBURG, Willemien       1     0       0
AARDEWIJN, Pepijn           0     0       1
AARONES, Ann Kristin        1     0       0
ABAJO, Jose Luis            1     0       0
...                       ...   ...     ...
ZYCH, Boguslaw              1     0       0
ZYKINA, Olesya              1     0       1
ZÜHLKE, Steffen             1     0       0
ZÜLOW, Andreas              0     1       0
ÖRSTED, Hans-Henrik         1     0       0

[11337 rows x 3 columns]

In [77]:
'Gold Silver Bronze Ranking'.split()

['Gold', 'Silver', 'Bronze', 'Ranking']

In [74]:
df = olimp.groupby(['Athlete', 'Medal']).size().unstack().fillna(0).astype('int')
df['Ranking'] = 6*df.Gold + 2*df.Silver + df.Bronze
df.sort_values(by='Ranking', ascending=False, inplace=True)
df = df['Gold Silver Bronze Ranking'.split()]
df.head(10)

Medal               Gold  Silver  Bronze  Ranking
Athlete
PHELPS, Michael       14       0       2       86
FISCHER, Birgit        8       4       0       56
LEWIS, Carl            9       1       0       56
THOMPSON, Jenny        8       3       1       55
BIONDI, Matthew        8       2       1       53
ANDRIANOV, Nikolay     6       4       2       46
SCHERBO, Vitaly        6       0       4       40
HALL, Gary Jr.         5       3       2       38
THORPE, Ian            5       3       1       37
COMANECI, Nadia        5       3       1       37

### 6.

Przyjmując ranking z punktu 5. wyświetl 10 najbardziej utytułowanych medalistów (dowolnej płci) w dyscyplinie *Swimming*.

In [79]:
df_2 = olimp.groupby(['Discipline', 'Athlete', 'Medal']).size()
df_2

Discipline       Athlete                 Medal
Archery          ARNOLD, Virginie        Bronze    1
                 ARZHANNIKOVA, Lyudmila  Bronze    1
                 BADENOV, Bair           Bronze    1
                 BARRS, Jay              Gold      1
                                         Silver    1
                                                  ..
Wrestling Gre-R  YLI-HANNUKSELA, Marko   Bronze    1
                                         Silver    1
                 YOLOUZ, Ghani           Silver    1
                 ZANDER, Thomas          Silver    1
                 ZAWADZKI, Wlodzimierz   Gold      1
Length: 13287, dtype: int64

In [80]:

swimming = df_2.loc['Swimming'].unstack().fillna(0).astype('int')
swimming.head()

Medal                       Bronze  Gold  Silver
Athlete
ABDO, Reema                      1     0       0
ABRAHAM, Gary                    1     0       0
ADLINGTON, Rebecca               0     2       0
ADRIAN, Nathan                   0     1       0
AHMANN-LEIGHTON, Christine       0     2       1

In [84]:
swimming['Ranking'] = 6*swimming.Gold + 2*swimming.Silver + swimming.Bronze
swimming.sort_values(by='Ranking', ascending=False, inplace=True)
swimming = swimming['Gold Silver Bronze Ranking'.split()]
swimming.head(10)

Medal             Gold  Silver  Bronze  Ranking
Athlete
PHELPS, Michael     14       0       2       86
THOMPSON, Jenny      8       3       1       55
BIONDI, Matthew      8       2       1       53
HALL, Gary Jr.       5       3       2       38
THORPE, Ian          5       3       1       37
OTTO, Kristin        6       0       0       36
TORRES, Dara         4       4       4       36
VAN DYKEN, Amy       6       0       0       36
POPOV, Alexander     4       5       0       34
PEIRSOL, Aaron       5       2       0       34

### 7.

Przyjmując ranking z punktu 5. wyświetl 10 najbardziej utytułowanych **medalistek** w dyscyplinie *Swimming*.

In [85]:
df_3 = olimp.groupby('Discipline Gender Athlete Medal'.split()).size()
df_3.head()

Discipline  Gender  Athlete          Medal
Archery     Men     BADENOV, Bair    Bronze    1
                    BARRS, Jay       Gold      1
                                     Silver    1
                    BISIANI, Matteo  Bronze    1
                                     Silver    1
dtype: int64

In [87]:
df_3.loc['Swimming']

Gender  Athlete                 Medal
Men     ABRAHAM, Gary           Bronze    1
        ADRIAN, Nathan          Gold      1
        ARMSTRONG, Duncan John  Gold      1
                                Silver    1
        ARVIDSSON, Pär          Gold      1
                                         ..
Women   ZHUANG, Yong            Gold      1
                                Silver    3
        ZIMMERMANN, Kathrin     Silver    1
        ZINDLER, Petra          Bronze    1
        ZSCHERPE, Iris          Bronze    1
Length: 996, dtype: int64

In [89]:
swimming = df_3.loc['Swimming'].unstack().fillna(0).astype('int')
swimming

Medal                          Bronze  Gold  Silver
Gender Athlete
Men    ABRAHAM, Gary                1     0       0
       ADRIAN, Nathan               0     1       0
       ARMSTRONG, Duncan John       0     1       1
       ARVIDSSON, Pär               0     1       0
       ASTBURY, Andrew              1     0       0
...                               ...   ...     ...
Women  ZHU, Yingwen                 0     0       1
       ZHUANG, Yong                 0     1       3
       ZIMMERMANN, Kathrin          0     0       1
       ZINDLER, Petra               1     0       0
       ZSCHERPE, Iris               1     0       0

[741 rows x 3 columns]

In [90]:
swimming = swimming.loc["Women", : ]
swimming.head()

Medal                       Bronze  Gold  Silver
Athlete
ABDO, Reema                      1     0       0
ADLINGTON, Rebecca               0     2       0
AHMANN-LEIGHTON, Christine       0     2       1
ALSHAMMAR, Therese               1     0       2
AMUNDRUD, Gail                   1     0       0